import type { Brand } from '@/types/brand';

function toKotlinName(str: string): string {
  const camel = str.replace(/[-_.](.)/g, (_, c: string) => c.toUpperCase());
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

function hexToKotlin(hex: string): string {
  const clean = hex.replace('#', '');
  const padded = clean.length === 3
    ? clean.split('').map((c) => c + c).join('')
    : clean.padStart(6, '0');
  return `0xFF${padded.toUpperCase()}`;
}

export function generateKotlin(brand: Brand): string {
  const shadcnCol = brand.collections.find((c) => c.id.startsWith('shadcn'));
  const primaryHex = shadcnCol?.tokens.find((t) => t.cssVariable === '--color-primary')?.values['light']?.raw ?? '';
  const hoverHex = shadcnCol?.tokens.find((t) => t.cssVariable === '--color-hover-primary')?.values['light']?.raw ?? '';
  const secondaryHex = shadcnCol?.tokens.find((t) => t.cssVariable === '--color-secondary')?.values['light']?.raw ?? '';

  const lines: string[] = [
    `// ${brand.name} Design Tokens`,
    `// Generated by Design Token Builder`,
    `// Date: ${new Date().toISOString().slice(0, 10)}`,
    ...(brand.primaryColorShade ? [`// Primary Color: primary-${brand.primaryColorShade} (${primaryHex})`] : []),
    ...(brand.secondaryColorShade ? [`// Secondary Color: secondary-${brand.secondaryColorShade} (${secondaryHex})`] : []),
    ``,
    `package com.${brand.slug.replace(/-/g, '.')}.designtokens`,
    ``,
    `import androidx.compose.ui.graphics.Color`,
    ``,
    `object ${toKotlinName(brand.name)}Tokens {`,
  ];

  for (const col of brand.collections) {
    const colorTokens = col.tokens.filter((t) => t.type === 'color');
    if (colorTokens.length === 0) continue;

    const objName = toKotlinName(col.name.replace(/[^a-zA-Z0-9]/g, '_'));
    lines.push(`  object ${objName} {`);

    for (const token of colorTokens) {
      const val = token.values['light'] ?? token.values['default'];
      if (!val?.raw.startsWith('#')) continue;
      const varName = token.name.replace(/[-.](.)/g, (_, c: string) => c.toUpperCase());
      const kotlinHex = hexToKotlin(val.raw);
      lines.push(`    val ${varName} = Color(${kotlinHex}.toInt())`);
    }

    lines.push(`  }`);
  }

  // Semantic brand color aliases
  if (primaryHex) {
    lines.push(`  // Semantic Brand Colors`);
    lines.push(`  object Brand {`);
    lines.push(`    val primary = Color(${hexToKotlin(primaryHex)}.toInt())`);
    if (hoverHex) lines.push(`    val hoverPrimary = Color(${hexToKotlin(hoverHex)}.toInt())`);
    if (secondaryHex && brand.secondaryColorShade) lines.push(`    val secondary = Color(${hexToKotlin(secondaryHex)}.toInt())`);
    lines.push(`  }`);
  }

  lines.push(`}`);
  return lines.join('\n');
}
