import type { Brand } from '@/types/brand';

function toCamelCase(str: string): string {
  return str.replace(/[-_.](.)/g, (_, c: string) => c.toUpperCase());
}

function toPascalCase(str: string): string {
  const camel = toCamelCase(str);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

export function generateSwift(brand: Brand): string {
  const shadcnCol = brand.collections.find((c) => c.id.startsWith('shadcn'));
  const primaryHex = shadcnCol?.tokens.find((t) => t.cssVariable === '--color-primary')?.values['light']?.raw ?? '';
  const hoverHex = shadcnCol?.tokens.find((t) => t.cssVariable === '--color-hover-primary')?.values['light']?.raw ?? '';
  const secondaryHex = shadcnCol?.tokens.find((t) => t.cssVariable === '--color-secondary')?.values['light']?.raw ?? '';

  const lines: string[] = [
    `// ${brand.name} Design Tokens`,
    `// Generated by Design Token Builder`,
    `// Date: ${new Date().toISOString().slice(0, 10)}`,
    ...(brand.primaryColorShade ? [`// Primary Color: primary-${brand.primaryColorShade} (${primaryHex})`] : []),
    ...(brand.secondaryColorShade ? [`// Secondary Color: secondary-${brand.secondaryColorShade} (${secondaryHex})`] : []),
    ``,
    `import UIKit`,
    `import SwiftUI`,
    ``,
    `extension UIColor {`,
    `  convenience init(hex: String) {`,
    `    var hex = hex.trimmingCharacters(in: .whitespacesAndNewlines).replacingOccurrences(of: "#", with: "")`,
    `    var int: UInt64 = 0`,
    `    Scanner(string: hex).scanHexInt64(&int)`,
    `    self.init(red: CGFloat((int >> 16) & 0xFF) / 255, green: CGFloat((int >> 8) & 0xFF) / 255, blue: CGFloat(int & 0xFF) / 255, alpha: 1)`,
    `  }`,
    `}`,
    ``,
    `enum ${toPascalCase(brand.name)}Tokens {`,
  ];

  for (const col of brand.collections) {
    const colorTokens = col.tokens.filter((t) => t.type === 'color');
    if (colorTokens.length === 0) continue;

    const colEnum = toPascalCase(col.name.replace(/[^a-zA-Z0-9]/g, '_'));
    lines.push(`  enum ${colEnum} {`);

    for (const token of colorTokens) {
      const val = token.values['light'] ?? token.values['default'];
      if (!val?.raw.startsWith('#')) continue;
      const varName = toCamelCase(token.name);
      lines.push(`    static let ${varName} = UIColor(hex: "${val.raw}")`);
    }

    lines.push(`  }`);
  }

  // Semantic brand color aliases
  if (primaryHex) {
    lines.push(`  // MARK: — Semantic Brand Colors`);
    lines.push(`  enum Brand {`);
    lines.push(`    static let primary = UIColor(hex: "${primaryHex}")`);
    if (hoverHex) lines.push(`    static let hoverPrimary = UIColor(hex: "${hoverHex}")`);
    if (secondaryHex && brand.secondaryColorShade) lines.push(`    static let secondary = UIColor(hex: "${secondaryHex}")`);
    lines.push(`  }`);
  }

  lines.push(`}`);
  lines.push(``);
  lines.push(`// SwiftUI Color extensions`);
  lines.push(`extension Color {`);
  for (const col of brand.collections) {
    const colorTokens = col.tokens.filter((t) => t.type === 'color');
    for (const token of colorTokens) {
      const val = token.values['light'] ?? token.values['default'];
      if (!val?.raw.startsWith('#')) continue;
      const varName = toCamelCase(`${col.name.replace(/[^a-zA-Z0-9]/g, '-')}-${token.name}`);
      lines.push(`  static let ${varName} = Color(UIColor(hex: "${val.raw}"))`);
    }
  }
  lines.push(`}`);

  return lines.join('\n');
}
